### ISSUE TITLE
Benchmark review 

### ISSUE THREAD

**Issue by 42hoch5086** [alexdedyura/cpu-benchmark#20]
Hi, I just want to get a quick feedback of my benchmark.

I have a Pi 3B+ with 1GB of RAM and a 32GB SD Card

When I run the benchmark, it says
CPU: unknown
Arch: unknown
OS: Linux 6.6.20+rpt-rpi-v8
Python: 3.11.2

the average Time is 245 seconds.

Can anyone tell me if this is good or if my Pi is really slow

Thanks,
RuntimeError5086 aka Danny

**Comment by alexdedyura** [comment]
It's ok, because Broadcom BCM2837B0 (CPU in RPi 3B+)  is slow. For good performance i recommended Orange Pi 5/5 Plus, it's powerful solution. I found the LinPack test, it shows how big the difference is between 3B+ and 4.
![image](https://github.com/alexdedyura/cpu-benchmark/assets/29916183/362bde83-b8e9-4efc-aaf6-e6381eb5f796)
